### ISSUE TITLE
TWG - Low Priority - Low Effort - Advanced INDEX token KPIs

### ISSUE THREAD

**Issue by jackiep00** [SetProtocol/index-coop-analytics#67] opened 2021-07-16 18:20 UTC
We have pretty advanced KPIs for each of our products, but we don't have the same KPIs for the INDEX token itself. We can fork the KPIs, but in addition to that, there are a few requests. I've split the requests into two groups - basic and advanced, and I'll create a separate issue for the basic ones. https://github.com/SetProtocol/index-coop-analytics/issues/84

Advanced KPIs (Python):
e) 7 day trading vol
f) 30 day trading vol
g) Standard deviation in token price against USD
h) Standard deviation in token price against ETH
i) Correlation coefficient INDEX to ETH over the last 90 days
j) Correlation coefficient INDEX to ETH since genesis

**Comment by ericlinML** [comment] 2021-08-10 00:04
Hey, if no one else has looked at this, I could easily do e-j with the pycoingecko API. I might try to look into how to get the data for a-d, but if anyone has any pointers, it would be much appreciated

**Comment by ericlinML** [comment] 2021-08-10 03:15
I got very curious and ended up doing subtasks e-j with pyCoinGecko (CoinGecko API). I'll make a pull request with a Jupyter Notebook and output CSV for this part. 

As of 8/9/2021: 
e. created rolling 7 day total trading vol and average trading vol
f. created rolling 30 day total trading vol and average trading vol
g. Since genesis, standard deviation of INDEX price has been $15.27 with 95% confidence interval (14.15,16.44). 
h. Measured in ETH, standard deviation of INDEX price has been 0.004698 ETH 95%CI (0, 0.01). I suspect there is a lower bound to reporting the bottom end of the 95% CI range.
i. Spearman's correlation coefficient of Index to ETH in the last 90 days has been r=0.872 95%CI [0.81, 0.91]
j. Spearman's correlation coefficient of Index to ETH since genesis has been r=0.878 95%CI [0.85, 0.9] 
* Spearman's was performed given that the two variables were not multivariate normal and thus unsuitable for Pearson's

**Comment by josephd8** [comment] 2021-08-10 13:32
Thanks @ericlinML for starting to take a stab at this! I think this might be something that we want built out on Dune Analytics for the time being, in order to provide a live dashboard surrounding the INDEX token. 

@jackiep00 - do you want to work with @ericlinML to narrow in on the scope for this and a path forward?

**Comment by ericlinML** [comment] 2021-08-10 23:42
It's not letting me attach an HTML file and generating a PDF would require installing a few more packages in the environment (which I could do if pressed). I think it's easier to point y'all to my cleaned up notebook with just figures and conclusions (https://github.com/ericlinML/index-coop-analytics/blob/index-token-kpi/kpis/index-token-kpi/oneTimeShowcase_8_10_2021.ipynb).

The runnable code generating these figures and stats (https://github.com/ericlinML/index-coop-analytics/blob/index-token-kpi/kpis/index-token-kpi/indexTokenKPIs.ipynb).

**Comment by jackiep00** [comment] 2021-08-11 01:30
Alright, that works. Thanks Eric!! Go ahead and pare down the PR to
whatever is feasible to check in - if the HTML file doesn't work then don't
worry about it.

Also, two more things: could you include the scatterplot of ETH price vs
INDEX price? And could you also show a chart of INDEX price as denominated
in ETH over time? The scatterplot seems like it's showing an ETH price
floor, and that INDEX is actually trading within a reasonably narrow ETH
band.

**Comment by ericlinML** [comment] 2021-08-11 15:24
Thanks for the great feedback! I've updated them as you requested and updated my fork, Yeah, the INDEX seems to only trade between ~ 0.005 ETH to 0.03 ETH per INDEX. I added a linear regression of INDEX (USD) as a function of ETH(USD) to the scatterplot b/c why not

**Comment by josephd8** [comment] 2021-08-16 22:55
@jackiep00 @ericlinML this corresponds to PR #82 , correct? As it stands, this will exist as python files that can be re-run as needed until we determine a longer term solution and need for these to be live.

I will leave a couple comments in the PR and we can work on closing this out. Thanks!

**Comment by ericlinML** [comment] 2021-08-17 04:58
@josephd8 @jackiep00 yes, you're correct. I'll leave all further comments within PR #82

**Closed** 2021-09-03 20:57 UTC
Labels: good first issue, treasury, in review
